### ISSUE TITLE
Rust port

### ISSUE THREAD

**Issue by thevilledev** [N-R-K/ChibiHash#2]
Kudos - super interesting project! Thank you for the great work.

I've created a Rust port of it at [thevilledev/ChibiHash-rs](https://github.com/thevilledev/ChibiHash-rs). I've tagged the first release as `v0.1.0` and published it as a [chibihash crate](https://crates.io/crates/chibihash).

I took your example key/seed combinations from your comment at https://github.com/N-R-K/ChibiHash/issues/1#issuecomment-2486086163 and [created a test for it](https://github.com/thevilledev/ChibiHash-rs/blob/main/src/lib.rs#L185-L197), to ensure we're on the right track.

Happy to keep maintaining the project and support anyone using this with Rust.

**Comment by N-R-K** [comment]
Thanks. I've added your repo the list of ports: https://github.com/N-R-K/ChibiHash/issues/4

**Comment by N-R-K** [comment]
Upon further look, I see there's an error depending on the size: https://github.com/thevilledev/ChibiHash-rs/blob/624b44991ba2ee8639b7e3de6e6acc4fbfe6fac3/src/lib.rs#L41-L46

Hash functions should *never* error. The trend in certain languages (especially those that have specific error types) to create unnecessary 'errors' is, IMO, a bad one. All it does is make the api cumbersome to use.

As for streaming api, you can do it with 0 allocations, keep a 32 byte buffer and append to it. See the newly pushed [stream branch](https://github.com/N-R-K/ChibiHash/blob/stream/chibihash64-stream.h) for reference. With fixed buffer, and allocation gone, the streaming api also cannot fail.

(In fact, I mixed the length into the state late in the hashing process instead of at the start specifically so that 0 allocation streaming apis are possible).

**Comment by thevilledev** [comment]
Thanks for the feedback! I was contemplating on removing the error type after implementing support for the [Hasher trait](https://doc.rust-lang.org/std/hash/trait.Hasher.html). It doesn't do errors either and the output is always `u64`. That's the standard. I'll likely remove the error type in the next release altogether. 👍 

I'll have a look at the streaming API!

**Comment by thevilledev** [comment]
Just a short follow-up. Streaming support added in [v0.2.0](https://crates.io/crates/chibihash). I'll keep an eye on the repo for any improvements/changes and incorporate them into my project as well. I'm looking into some Rust-specific optimisations too.

**Comment by N-R-K** [comment]
> Just a short follow-up. Streaming support added in [v0.2.0](https://crates.io/crates/chibihash). I'll keep an eye on the repo for any improvements/changes and incorporate them into my project as well.

Good to know. I've made some local changes to improve short string performance which will be part of v2 (I will make a new branch for it when things are more polished).

> I'm looking into some Rust-specific optimisations too.

Do you have any numbers on how the rust port compares to the C version? I'd assume they're on the same league since rust is backed by llvm (which is more or less on par with gcc).

**Comment by thevilledev** [comment]
> Do you have any numbers on how the rust port compares to the C version? I'd assume they're on the same league since rust is backed by llvm (which is more or less on par with gcc).

I went ahead and implemented a small test suite, which calls the original C implementation of the hash function through Rust's [FFI (Foreign Function Interface)](https://doc.rust-lang.org/rust-by-example/std_misc/ffi.html). I ran both implementations through the benchmarks on various input sizes. I included a few screenshots and thoughts in https://github.com/thevilledev/ChibiHash-rs/pull/9#issuecomment-2492087085.

Despite the results of Rust being faster on smaller input sizes, I'd consider both more or less the same. If I'd have to guess there is some overhead of FFI which makes those smaller input size runs seem slower on the C implementation.
